src/blog/urls.py
'''
blog/urls
'''
from django.urls import include, path
from blog.views import BlogIndex, BlogDetail, ListPostsByTag

urlpatterns = [
    path(r'', BlogIndex.as_view(), name='blog_index'),  # Blog Index
    path(r'<slug>', BlogDetail.as_view(), name="entry_detail"),  # Blog Detail
    path(r'tag/<str:tag>', ListPostsByTag.as_view(),name='list_by_tag'),
]

src/hub/urls.py
'''
hub/urls
'''
from django.urls import path
from .views import ProiecteIndex, ProiecteDetail

urlpatterns = [
    path(r'', ProiecteIndex.as_view(), name='proiecte_index'),
    path(r'<slug>', ProiecteDetail.as_view(), name="proiecte_detail"),
    # path(r'resurse/<slug>', ResurseDetail.as_view(), name="resurse_detail"),
    # path(r'resurse/', ResurseIndex.as_view(), name='resurse_index'),

    # membership, feature not offered yet. No link to this page.
    # path(r'membership/', membership, name='membership'),
]

src/blog/models.py
'''
Models of the blog section
-Blog posts
-Tags
'''
from __future__ import unicode_literals
from django.db import models
from django_markdown.models import MarkdownField  # to fix markdown
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model


class Tag(models.Model):
    '''
    Tag. A class that is assigned to one ore more blog posts to classifiy it.
    A blog post can have more tags.
    A tag is defined by one single slug.
    '''
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        verbose_name_plural = "Tag-uri"

    def __str__(self):
        return self.slug


class EntryQuerySet(models.QuerySet):
    '''
    A query set model.
    '''
    def published(self):
        '''
        Return blog posts that are published
        '''
        return self.filter(publish=True)


def get_sentinel_user():
    '''
    Get a default user 'sters' in case a post has no user.
    '''
    return get_user_model().objects.get_or_create(username='sters')[0]


class Entry(models.Model):
    '''
    Blog post.
    '''
    title = models.CharField(max_length=100)
    subtitle = models.CharField(max_length=400)
    body = MarkdownField()
    slug = models.SlugField(max_length=200, unique=True)
    publish = models.BooleanField(default=True)
    author = models.ForeignKey(User, on_delete=models.SET(get_sentinel_user), default=0)
    created = models.DateTimeField()
    modified = models.DateTimeField(auto_now=True)
    tags = models.ManyToManyField(Tag)
    objects = EntryQuerySet.as_manager()
    image = models.ImageField(upload_to='postImage', blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        '''
        Get absolute url of object blog entry (post)
        '''
        return reverse("entry_detail", kwargs={"slug": self.slug})

    class Meta:
        '''
        Romanian titles.
        '''
        verbose_name = "Postare din Blog"
        verbose_name_plural = "Postari din Blog"
        ordering = ["-created"]

src/blog/views.py
'''
Blog/views
'''
from django.views import generic
from django.views.generic import TemplateView
from blog.models import Entry, Tag
from django.shortcuts import render, redirect


class BlogIndex(generic.ListView):
    '''
    ListView to display blog posts with pagination
    '''
    template_name = "blog_index_element.html"
    paginate_by = 10

    def get_context_data(self, **kwargs):
        '''
        Get blog posts that are published
        Customized query set
        '''
        context = super(BlogIndex, self).get_context_data(**kwargs)
        context['Entry'] = Entry.objects.published()
        context['tags'] = Tag.objects.all()
        return context

    def get_queryset(self):
        return Entry.objects.published().select_related('author')



class BlogDetail(generic.DetailView):
    '''
    BlogDetail(generic.DetailView)
    '''
    model = Entry
    template_name = "blog_post.html"

    def get_context_data(self, **kwargs):
        context = super(BlogDetail, self).get_context_data(**kwargs)
        context['tags'] = Tag.objects.all()
        return context



class AddPost(TemplateView):
    '''
    AddPost(TemplateView)
    '''
    template_name = "addPost.html"

class ListPostsByTag(TemplateView):

    template_name = 'list_posts_by_tag.html'

    def get(self, request, *args, **kwargs):
        tag_url = kwargs['tag']
        posts = Entry.objects.filter(tags__slug=tag_url)
        tags = Tag.objects.all()
        return render(request, self.template_name, {'posts':posts,'query':tag_url,'tags':tags})

def search(request):
    query = request.GET.get('q')
    object_list = Entry.objects.filter(Q(tags__slug=query))
    print(object_list)
    return render(request,'list_posts_by_tag.html',{'object_list':object_list,'query':query})

src/blog/templates/blog_base.html
{% extends 'base.html' %}

{% load static %}

{% block metatags %}
    <meta name="description" content="{% block metadesc %}Selfpower.ro - Blog, Articole, Studii{% endblock metadesc %}">
    <meta name="keywords" content="Selfpower, Blog, Articole, Studii, Consiliere, Educatie, Dezvoltare, Personala">
    <meta property="og:title" content="{% block metatitle %}Selfpower.ro Blog{% endblock metatitle %}" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="https://www.selfpower.ro/blog/{% block og_url %}{% endblock og_url %}" />
    <meta property="og:description" content="Selfpower.ro - Blog, Articole, Studii" />
    <meta property="og:image" content="https://www.selfpower.ro/static/img/banner.png" />
    <meta property="og:image:secure_url" content="https://www.selfpower.ro/static/img/banner.png" />
    <meta property="og:image:type" content="image/png" />
    <meta property="og:image:alt" content="Blog Selfpower Banner Image" />
    <meta property="og:image:width" content="1000" />
    <meta property="og:image:height" content="532" />
    <meta property="fb:app_id" content="2521504124841472" />
{% endblock metatags %}




{% block title %} Selfpower - Blog, Articole, Studii {% endblock title %}

{% block body %} <body id="blog"> {% endblock body %}

{% block content %}

    <div class="container">

        <div class="box">

                {% block blog_entries %} {% endblock %}

        </div><!-- /.box -->

    </div>
    <!-- /.container -->

{% endblock content %}

src/blog/templates/blog_index_element.html
{% extends "blog_base.html" %}
{% load static %}

{% block metatags %}
    <meta name="description" content="{% block metadesc %}Selfpower.ro - Blog, Articole, Studii, Index{% endblock metadesc %}">
    <meta name="keywords" content="Selfpower, Blog, Articole, Studii, Consiliere, Educatie, Dezvoltare, Personala">
    <meta property="og:title" content="{% block metatitle %}Selfpower Blog - Articole despre Consiliere, Educatie si Dezvoltare Personala{% endblock metatitle %}" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="https://www.selfpower.ro/blog/{% block og_url %}{% endblock og_url %}" />
    <meta property="og:description" content="Selfpower - Blog, Articole, Studii" />
    <meta property="og:image" content="https://www.selfpower.ro/static/img/banner.png" />
    <meta property="og:image:secure_url" content="https://www.selfpower.ro/static/img/banner.png" />
    <meta property="og:image:type" content="image/png" />
    <meta property="og:image:alt" content="Blog Selfpower Banner Image" />
    <meta property="og:image:width" content="1000" />
    <meta property="og:image:height" content="532" />
    <meta property="fb:app_id" content="2521504124841472" />
{% endblock metatags %}

{% block title %}Selfpower Blog - Articole despre Consiliere, Educatie si Dezvoltare Personala{% endblock title %}

{% block body %} <body id="blog"> {% endblock body %}


{% block content %}

<div class="container">
<div class="row">
<div class="box">
    <div class="col-lg-10 col-lg-offset-1">
        <hr>
        <h2 class="intro-text text-center"><strong>Articole </strong>
            Selfpower
        </h2>
        <hr>
        {%include "tag_list.html" %}
        {% block tag %}
        {% endblock %}
    </div>
</div><!-- ./box -->
</div><!-- ./row -->
</div><!-- ./container-->


<div class="container">
  {% for object in object_list %}
    <div class="row">
        <div class="box">
          <div class="col-lg-10 col-lg-offset-1">
            <br>
            <h2 class="text-center">
              <a href="{% url "entry_detail" slug=object.slug %}">{{ object.title }}</a>
            </h2>
            <br>
            <a href="{% url "entry_detail" slug=object.slug %}">
            {% if object.image %}
              <img src=" {{ object.image.url }} " alt="Blog Image" class="img-responsive center-block" style="width: 70%;">
            {% else %}
              <img src="{% static "img/blogimage.jpg" %}" alt="Blog Image" class="img-responsive center-block" style="width: 70%;">
            {% endif %}
            </a>
              <br>
            <p class="text-center" style="color: #837777;">
               <i> {{ object.subtitle }} </i>
            </p>
          </div>
      </div>
    </div>
  {% endfor %}
</div>



{% if is_paginated %}
<div class="row">
<div class="col-md-10 col-md-offset-1 text-center">
    <ul class="pager">
        <li {% if not page_obj.has_previous %} class="previous disabled" {% else %} class="previous" {% endif %}>
          <a {% if page_obj.has_previous %}href="?page={{ page_obj.previous_page_number }}"{% endif %}>&larr; Precedent</a>
        </li>
        <li {% if not page_obj.has_next %} class="next disabled" {% else %} class="next" {% endif %}>
          <a {% if page_obj.has_next %}href="?page={{ page_obj.next_page_number }}"{% endif %}>Următor &rarr;</a>
        </li>
    </ul>
</div>
</div><!-- /.row -->

{% endif %}

{% endblock %}

src/blog/templates/blog_post.html
{% extends "blog_base.html" %}
{% load django_markdown %}
{% load static %}

{% block metatags %}
    <meta name="description" content="{% block metadesc %}{% if object.subtitle %}{{ object.subtitle }}{% else %}Selfpower.ro Blog Post{% endif %}{% endblock metadesc %}">
    <meta name="keywords" content="Selfpower, Blog, Post, Articol, {% for t in object.tags.all %}{{t.slug}}{% endfor %}">
    <meta name="article:author" content="{% if object.author.get_full_name %}{{ object.author.get_full_name }}{% else %} by Selfpower.ro{% endif %}">
    <meta property='article:publisher' content='https://www.selfpower.ro/' />
    <meta property='og:site_name' content='Asociatia Selfpower' />
    <meta property="og:type" content="article" />
    <meta property="og:url" content="{{ request.scheme }}://{{request.META.HTTP_HOST}}/blog/{{ object.slug }}" />
    <meta property="og:title" content="{% block metatitle %}{% if object.title %}{{ object.title }}{% else %}Selfpower.ro Blog Post{% endif %}{% endblock metatitle %}" />
    <meta property="og:description" content="{% if object.subtitle %}{{ object.subtitle }}{% else %}Selfpower.ro Blog Post{% endif %}" />
    <meta property="og:image" content="{% if object.image %}{{ request.scheme }}://{{request.META.HTTP_HOST}}{{ object.image.url }}{% else %}https://www.selfpower.ro/static/img/banner.png{% endif %}" />
    <meta property="og:image:secure_url" content="{% if object.image %}{{ request.scheme }}://{{request.META.HTTP_HOST}}{{ object.image.url }}{% else %}https://www.selfpower.ro/static/img/banner.png{% endif %}" />
    <meta property="og:image:type" content="{% if object.image %}image/jpg{% else %}image/png{% endif %}" />
    <meta property="og:image:alt" content="Blog Post Image" />
    {% if object.image %}
    {% else %}
    <meta property="og:image:width" content="1000" />
    <meta property="og:image:height" content="532" />
    {% endif %}
    <meta property="fb:app_id" content="2521504124841472" />
{% endblock metatags %}


{% block title %}  {{ object.title }} {% endblock title %}

{% block blog_entries %}

  <div class="row">
      <div class="col-lg-10 col-lg-offset-1">
          <hr>
          <h2 class="intro-text text-center"><strong>Articol</strong>
              Selfpower
          </h2>
          
        <hr>    
      </div>
  </div><!-- ./row -->
  <div class="row">
      <div class="col-md-10 col-md-offset-1">
        <div id="mycarousel" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner">
            <div class="item active">
              {% if object.image %}
                <img src=" {{ object.image.url }} " alt="Blog Image" class="img-responsive center-block" style="width: 70%;">
              {% else %}
                <img src="{% static "img/blogimage.jpg" %}" alt="Blog Post Image" class="img-responsive center-block" style="width: 90%;">
              {% endif %}
            </div>
          </div><!-- ./carousel-inner -->
        </div><!-- ./mycarousel -->
      </div><!-- ./col-md-10 -->
  </div><!-- ./row -->

  <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <div class="blogpost">
          <h2 class="text-center">{{object.title}}</h2>
              <br>
              <p class="text-center" style="color: #837777;">
                 <i> {{ object.subtitle }} </i>
              </p>
              <hr>
          {{ object.body | markdown }}

        </div><!-- ./blogpost -->

        <div class="blogpost">
          <hr>
          <p class="text-center">
            <small><!-- All of this for Author -->
              autor:
                 <b>
                   {{ object.author.get_full_name|default:object.author.username }}
                 </b>
               , publicat:
                <b>
                 {{ object.created }}
                </b>
            </small>
          </p>
          <ul class="pager">
                <li>
                  <a href="{% url 'blog_index' %}">&larr; Cuprins</a>
                </li>
          </ul><!-- ./pager -->
          <hr>
          <h2 class="intro-text text-center">
            {% for tag in object.tags.all %}
            <span class="label label-warning" style="display:inline-flex">
              <a style="text-decoration: none;" href="{% url 'list_by_tag' tag %}">#{{tag.slug}}</a>
            </span>
            {% endfor %}
   
          </h2>
        </div><!-- ./blogpost -->
        <hr>
      </div><!-- ./col-md-8 -->
  </div><!-- ./row -->

  <div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div id="disqus_thread"></div>
        <script>
        /**
        *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
        *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
        var disqus_config = function () {
        this.page.url = 'https://selfpower.ro{% url "entry_detail" slug=object.slug %}';  // Replace PAGE_URL with your page's canonical URL variable
        this.page.identifier = 'selfpower-blog-post-{{ object.slug }}'; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
        };
        (function() { // DON'T EDIT BELOW THIS LINE
        var d = document, s = d.createElement('script');
        s.src = 'https://selfpower-ro.disqus.com/embed.js';
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
        })();
        </script>
        <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
    </div>
  </div><!-- ./row -->







{% include 'modalDonations.html' %}

 <!-- this code displays an alert box if this is the first time when the user access this page. uses cookies. -->
<script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
<script>

function s()
{
    $('#prizePopup').modal('show');
}


var cookies = document.cookie.split(';');//contains all the cookies
var cookieName = ['access']; // to contain name of all the cookies
for(i=0;i<cookies.length;i++) {
    cookieName[i] = cookies[i].split('=')[0].trim();
}

    if(cookieName.indexOf('access')>-1) {
        console.log("This is NOT first access");
    } else {
        console.log("First Access");
        document.cookie = "access=yes";
        $(window).load(function()
        {
          setTimeout(s, 40000);
        });
    }
</script>



{% endblock %}

src/blog/templates/blog_search_tag.html
{% extends "blog_base.html" %}
{% load static %}

{% block metatags %}
    <meta name="description" content="{% block metadesc %}Selfpower.ro - Blog, Articole, Studii, Index{% endblock metadesc %}">
    <meta name="keywords" content="Selfpower, Blog, Articole, Studii, Consiliere, Educatie, Dezvoltare, Personala">
    <meta property="og:title" content="{% block metatitle %}Selfpower Blog - Articole despre Consiliere, Educatie si Dezvoltare Personala{% endblock metatitle %}" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="https://www.selfpower.ro/blog/{% block og_url %}{% endblock og_url %}" />
    <meta property="og:description" content="Selfpower - Blog, Articole, Studii" />
    <meta property="og:image" content="https://www.selfpower.ro/static/img/banner.png" />
    <meta property="og:image:secure_url" content="https://www.selfpower.ro/static/img/banner.png" />
    <meta property="og:image:type" content="image/png" />
    <meta property="og:image:alt" content="Blog Selfpower Banner Image" />
    <meta property="og:image:width" content="1000" />
    <meta property="og:image:height" content="532" />
    <meta property="fb:app_id" content="2521504124841472" />
{% endblock metatags %}

{% block title %}Selfpower Blog - Articole despre Consiliere, Educatie si Dezvoltare Personala{% endblock title %}

{% block body %} <body id="blog"> {% endblock body %}


{% block content %}

<div class="container">
<div class="row">
<div class="box">
    <div class="col-lg-10 col-lg-offset-1">
        <hr>
        <h2 class="intro-text text-center"><strong>Articole </strong>
            Selfpower
        </h2>
        <div class="text-center">
        <span class="h3 intro-text">
          <span class="label label-warning"> 
              <strong><a href="{% url 'list_by_tag' query %}">#{{query}}</a></strong>
          </span>
        </span>
      </div>
        <hr>
        {%include "tag_list.html" %}
        {% block tag %}
        {% endblock %}
    </div>
</div><!-- ./box -->
</div><!-- ./row -->
</div><!-- ./container-->


<div class="container">
  {% for object in posts %}
    <div class="row">
        <div class="box">
          <div class="col-lg-10 col-lg-offset-1">
            <br>
            <h2 class="text-center">
              <a href="{% url "entry_detail" slug=object.slug %}">{{ object.title }}</a>
            </h2>
            <br>
            <a href="{% url "entry_detail" slug=object.slug %}">
            {% if object.image %}
              <img src=" {{ object.image.url }} " alt="Blog Image" class="img-responsive center-block" style="width: 70%;">
            {% else %}
              <img src="{% static "img/blogimage.jpg" %}" alt="Blog Image" class="img-responsive center-block" style="width: 70%;">
            {% endif %}
            </a>
              <br>
            <p class="text-center" style="color: #837777;">
               <i> {{ object.subtitle }} </i>
            </p>
          </div>
      </div>
    </div>
  {% endfor %}
</div>



{% if is_paginated %}
<div class="row">
<div class="col-md-10 col-md-offset-1 text-center">
    <ul class="pager">
        <li {% if not page_obj.has_previous %} class="previous disabled" {% else %} class="previous" {% endif %}>
          <a {% if page_obj.has_previous %}href="?page={{ page_obj.previous_page_number }}"{% endif %}>&larr; Precedent</a>
        </li>
        <li {% if not page_obj.has_next %} class="next disabled" {% else %} class="next" {% endif %}>
          <a {% if page_obj.has_next %}href="?page={{ page_obj.next_page_number }}"{% endif %}>Următor &rarr;</a>
        </li>
    </ul>
</div>
</div><!-- /.row -->

{% endif %}

{% endblock %}

src/blog/templates/list_posts_by_tag.html
{% extends "blog_base.html" %}
{% load static %}

{% block metatags %}
    <meta name="title" content="Selfpower Blog - Articole despre {{query}}">
    <meta name="description" content="{% block metadesc %}Selfpower.ro - Blog, Articole, Studii, Index{% endblock metadesc %}">
    <meta name="keywords" content="Selfpower, Blog, Articole, {{query}}">
    <meta property="og:title" content="{% block metatitle %}Selfpower Blog - Articole despre {{query}}{% endblock metatitle %}" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="https://www.selfpower.ro/blog/{% block og_url %}{% endblock og_url %}" />
    <meta property="og:description" content="Selfpower - Blog, Articole, Studii" />
    <meta property="og:image" content="https://www.selfpower.ro/static/img/banner.png" />
    <meta property="og:image:secure_url" content="https://www.selfpower.ro/static/img/banner.png" />
    <meta property="og:image:type" content="image/png" />
    <meta property="og:image:alt" content="Blog Selfpower Banner Image" />
    <meta property="og:image:width" content="1000" />
    <meta property="og:image:height" content="532" />
    <meta property="fb:app_id" content="2521504124841472" />
{% endblock metatags %}

{% block title %}Selfpower Blog - Articole despre {{query}}{% endblock title %}

{% block body %} <body id="blog"> {% endblock body %}


{% block content %}

<div class="container">
<div class="row">
<div class="box">
    <div class="col-lg-10 col-lg-offset-1">
        <hr>
        <h2 class="intro-text text-center"><strong>Articole </strong>
            Selfpower
        </h2>
        <hr>
        <div class="text-center">
        <span class="h3 intro-text">
          <p style="font-size: 14px; display:inline-block" >Posturi despre:</p>
          <span class="label label-warning"> 
               <strong style="color:#fff3ea">#{{query}}</strong>
          </span>
        </span>
      </div>
        
        <!-- {%include "tag_list.html" %}
        {% block tag %}
        {% endblock %} -->
    </div>
</div><!-- ./box -->
</div><!-- ./row -->
</div><!-- ./container-->


<div class="container">
  {% for object in posts %}
    <div class="row">
        <div class="box">
          <div class="col-lg-10 col-lg-offset-1">
            <br>
            <h2 class="text-center">
              <a href="{% url "entry_detail" slug=object.slug %}">{{ object.title }}</a>
            </h2>
            <br>
            <a href="{% url "entry_detail" slug=object.slug %}">
            {% if object.image %}
              <img src=" {{ object.image.url }} " alt="Blog Image" class="img-responsive center-block" style="width: 70%;">
            {% else %}
              <img src="{% static "img/blogimage.jpg" %}" alt="Blog Image" class="img-responsive center-block" style="width: 70%;">
            {% endif %}
            </a>
              <br>
            <p class="text-center" style="color: #837777;">
               <i> {{ object.subtitle }} </i>
            </p>
          </div>
      </div>
    </div>
  {% endfor %}
</div>



{% if is_paginated %}
<div class="row">
<div class="col-md-10 col-md-offset-1 text-center">
    <ul class="pager">
        <li {% if not page_obj.has_previous %} class="previous disabled" {% else %} class="previous" {% endif %}>
          <a {% if page_obj.has_previous %}href="?page={{ page_obj.previous_page_number }}"{% endif %}>&larr; Precedent</a>
        </li>
        <li {% if not page_obj.has_next %} class="next disabled" {% else %} class="next" {% endif %}>
          <a {% if page_obj.has_next %}href="?page={{ page_obj.next_page_number }}"{% endif %}>Următor &rarr;</a>
        </li>
    </ul>
</div>
</div><!-- /.row -->

{% endif %}

{% endblock %}

src/blog/templates/tag_list.html
<h2 class="intro-text text-center">
    {% for tag in tags %}
        <span class="span-spacing label label-warning text-center">
            <a style="text-decoration: none;" href="{% url 'list_by_tag' tag %}">#{{tag.slug}}</a>
        </span>
        &nbsp;
    {% endfor %}
</h2>