src/home/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views import home, MembersView

urlpatterns = [
    path(r'despre/', home, name='about'),

    path(r'membri/', MembersView.as_view(), name='membri'),

    path(r'parteneri/', TemplateView.as_view(template_name='parteneri.html'), name='parteneri'),
]

src/hub/urls.py
'''
hub/urls
'''
from django.urls import path
from .views import ProiecteIndex, ProiecteDetail

urlpatterns = [
    path(r'', ProiecteIndex.as_view(), name='proiecte_index'),
    path(r'<slug>', ProiecteDetail.as_view(), name="proiecte_detail"),
    # path(r'resurse/<slug>', ResurseDetail.as_view(), name="resurse_detail"),
    # path(r'resurse/', ResurseIndex.as_view(), name='resurse_index'),

    # membership, feature not offered yet. No link to this page.
    # path(r'membership/', membership, name='membership'),
]

src/home/models.py
'''
home/views
'''
# from django.db import models
# from django.conf import settings

src/home/forms.py
'''
home/forms
'''
from django import forms


class SignUpForm(forms.Form):
    '''
    Sign up form . First step in the sign up process
    It precedes an activation link sent by email to the new user.
    '''
    adresa_email = forms.EmailField()
    checkbox_agreement = forms.BooleanField()

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(SignUpForm, self).__init__(*args, **kwargs)

    def clean(self):

        message = 'Pentru utilizarea serviciului de newsletter este necesară confirmarea acordului dvs.'

        if not "checkbox_agreement" in self.request.POST:
            raise forms.ValidationError(
                        (message)
                    )
            
        checkbox_agreement = self.cleaned_data['checkbox_agreement']

        if checkbox_agreement==False:
            raise forms.ValidationError(
                        (message)
                    )

src/home/views.py
'''
home/views
Web views: home
Tasks:
-update() which updates the status of a navigator
-isSubscribed() check the status of a navigator
encoding: utf-8
'''
import json
import requests

from django.shortcuts import render
from django.contrib import messages
from django.conf import settings
from django.views.generic import TemplateView

from mailchimp3 import MailChimp

from SelfpowerProject.settings.utils import convert_text_to_md5
from .forms import SignUpForm
from blog.models import Tag

API_KEY = settings.MAILCHIMP_API
LIST_ID = settings.MAILCHIMP_LIST_ID


def update(subscriber_email, subscribeOrUnsubscribe):
    '''
    Update the status of subscriber to
    -subscribed
    -unsubscribed
    '''
    try:
        subscriber_hash = convert_text_to_md5(subscriber_email)

        authorization = 'Basic YWxleDplZjZiNzBjMDAzYTk3ZmVkZDJiYWI1OTE2ODcwZDZiMi11czEw'

        headers = {
            'Authorization': authorization,
        }

        payload = {
            "status": subscribeOrUnsubscribe
        }
        url = 'https://us10.api.mailchimp.com/3.0/lists/281deb4d67/members/'+subscriber_hash
        response = requests.patch(
                        url, headers=headers,
                        data=json.dumps(payload)
                        )
        response.raise_for_status()
        return 1  # reabonarea s-a facut cu succes prin API
    except Exception as e:
        return 0  # reabonarea nu s-a putut face prin API si userul trebuie
        # sa se reaboneze singur prin emailul primit de la mailchimp


def isSubscribed(subscriber_email):
    '''
    verify if the navigator is already subscribed in the newsletter list
    '''
    cond = True
    authorization = 'Basic YWxleDplZjZiNzBjMDAzYTk3ZmVkZDJiYWI1OTE2ODcwZDZiMi11czEw'
    subscriber_hash = convert_text_to_md5(subscriber_email)
    headers = {
                'Authorization': authorization
                }
    url = 'https://us10.api.mailchimp.com/3.0/lists/281deb4d67/members/'+subscriber_hash
    response = requests.patch(url, headers=headers)

    if response.json()['status'] == 'subscribed':
        cond = True
    else:
        cond = False

    return cond




def home(request):
    '''
    Web view
    Contains MailChimp form
    '''
    # print(client.lists.members.all(LIST_ID, get_all=False))

    if request.method == 'POST':

        try:
        
            client = MailChimp(mc_api=API_KEY, mc_user='office')

            Nform = SignUpForm(data=request.POST, request=request)
            if Nform.is_valid():
                new_email_address = Nform.cleaned_data['adresa_email']
                try:
                    client.lists.members.create(
                        LIST_ID, {
                            'email_address': new_email_address,
                            'status': 'subscribed',
                            'double_option': True,
                            'update_existing': False,
                            'send_welcome': True,
                            })
                    messages.success(request, 'Mulțumim pentru înregistrare')
                    return render(request, 'about.html', {'form': Nform, 'anchor': 'inregistrare'})

                except Exception as e:
                    # print(e.args[0]['title'])
                    if(e.args[0]['title'] == "Member Exists"):
                        if(isSubscribed(new_email_address)):
                            messages.error(request, "Membrul exisă deja și este abonat!")
                        else:
                            response = update(new_email_address, 'subscribed')
                            if response == 1:
                                messages.success(request, "Membrul deja existent a fost reabonat!")
                            else:
                                messages.error(request, "Se pare ca acest email a fost dezabonat. Pentru reabonare, folositi emailul primit dupa dezabonare si urmariti linkul.")
                    else:
                        messages.error(request,  e.args[0]['title'])

            else:
                messages.error(request, 'Formular incorect, vă rugăm să verificați din nou')
                return render(request, 'about.html', {'form': Nform, 'anchor': 'inregistrare'})

        except Exception as exception:
            print(exception)
            messages.error(request, exception)
            return render(request, 'about.html')
    else:
        Nform = SignUpForm()
        tags = Tag.objects.all()
    return render(request, 'about.html', {'form': Nform,'tags':tags})


class MembersView(TemplateView):
    """
    Display members of the team
    """
    template_name = "membri.html"

src/home/templates/about.html
{% extends 'base.html' %}

{% block metatags %}
    <meta name="description" content="Despre Noi si Despre Selfpower comunitatea de consiliere si dezvoltare personala. Psiholog Consilier Profesor">
    <meta name="keywords" content="Selfpower, Despre, Noi, Colaboratori, Parteneri">
    <meta property="og:title" content="Despre - Selfpower Consiliere, Educatie si Dezvoltare Personala" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="https://www.selfpower.ro/about" />
    <meta property="og:description" content="Despre Noi si Despre Selfpower, comunitatea de consiliere si dezvoltare personala. Psiholog Consilier Profesor" />
    <meta property="og:image" content="https://www.selfpower.ro/static/img/ParkGreenxs.jpg" />
    <meta property="og:image:secure_url" content="https://www.selfpower.ro/static/img/ParkGreenxs.jpg" />
    <meta property="og:image:type" content="image/jpeg" />
    <meta property="og:image:width" content="717" />
    <meta property="og:image:height" content="403" />

{% endblock metatags %}
{% block title %} Despre Noi - Selfpower Consiliere, Educatie si Dezvoltare Personala{% endblock title %}

{% load static %}

{% block body %} <body id="home"> {% endblock body %}

{% block content %}

    <div class="container">

        <div class="row">
            <div class="box">
                <div class="col-lg-10 col-lg-offset-1 text-center">
                <img src="{% static "img/banner.png" %}" alt="Blog Image" class="img-responsive center-block">
                </div>
            </div>
        </div>

        <div class="row">
            <div class="box">
                <div class="col-lg-10 col-lg-offset-1">
                    <hr>
                    <h2 class="intro-text text-center"><strong>Despre</strong>
                        Selfpower
                    </h2>
                    <hr>
                </div>
                <div class="col-lg-6 col-lg-offset-3 text-center">
                    <p class="frontpage">
                      &nbsp; &nbsp; Asociația Selfpower oferă servicii de psihoterapie, educație și management al stilului de viață.
                      Scopul nostru principal este creșterea nivelului de confort psihic, emoțional și social al celor interesați.
                    </p>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>

        <div class="row">
            <div class="box">
                <div class="col-lg-10 col-lg-offset-1">
                    <hr>
                    <h2 class="intro-text text-center"><strong>Parteneri</strong>
                        Selfpower
                    </h2>
                    <hr>
                </div>

              <div class="row">
                  <div class="col-xs-4">
                      <a href="https://www.goethe.de/ins/ro/de/index.html" class="thumbnail">
                          <img src="{% static 'img/Goethe.png' %}" alt="Goethe_institut" style="max-height:225px">
                      </a>
                  </div>
                  <div class="col-xs-4">
                      <a href="https://www.goethe.de/prj/cma/en/index.html" class="thumbnail">
                          <img src="{% static 'img/CMA_en.jpg' %}" alt="CMA_en" style="max-height:225px">
                      </a>
                  </div>
                  <div class="col-xs-4">
                      <a href="https://www.liceulnational.ro/" class="thumbnail">
                          <img src="{% static 'img/ltn2.jpg' %}" alt="LTN2" style="max-height:225px">
                      </a>
                  </div>
              </div>

            </div>
        </div>

        <div class="row">
            <div class="box">
                <div class="col-lg-10 col-lg-offset-1">
                    <hr>
                    <h2 class="intro-text text-center"><strong>Tag-uri</strong>
                        de blog
                    </h2>
                    <hr>
                    {%include "tag_list.html" %}
                    {% block tag %}
                    {% endblock %}
                </div>
            </div>
            </div>
        </div>
        


        <div class="row">
            <div class="box">
                <div class="col-lg-6 col-lg-offset-3 text-center">
                    <hr>
                    <p class="frontpage">"M-am str&#259;duit ne&#238;ncetat s&#259; nu ridiculizez, s&#259; nu depl&#226;ng <br>&#351;i nici s&#259; dispre&#355;uiesc ac&#355;iunile umane, ci s&#259; le în&#355;eleg."<br>Spinoza</p>
                    <hr>
                </div>
            </div>
        </div>




<script>
function formInteracted(cond)
{
   // if(cond)
   // {
   //     t = document.getElementsByClassName("id1")[0]
   //     t.style.color = 'red'
   //     widget = document.getElementsByClassName("g-recaptcha")[0]
   //     widget.style.visibility='visible'
   // }
   // else
   // {
   //     t = document.getElementsByClassName("id1")[0]
   //     t.style.color = 'black'
   //     widget = document.getElementsByClassName("g-recaptcha")[0]
   //     widget.style.visibility='hidden'
   // }

   var item = document.getElementsByClassName("g-recaptcha")[0]

   if(cond)
   {

        item.classList.add('is-visibleAK');

        setTimeout(function ()
        {
          item.classList.add('is-openAK');
        }, 20);
   }
   else
   {}
}
</script>


    <div class="row" onmouseover="formInteracted(true)">
        <div class="box" >
            <div class="row">
            <form id="inregistrare" class="form-inline text-center" method="post">
              {% csrf_token %}
                <div class="form-group">
                  <label for="id_adresa_email">Newsletter:</label>

                  <input type="email" class="form-control" name="adresa_email" id="id_adresa_email" placeholder="nume@nume.com">

                  </div>
                <button type="submit" class="btn btn-default">Înscriere</button>

                <br>
                <br>


                <input type="checkbox" name="checkbox_agreement" id="checkbox_agreement"> {{ config.aproveNewsletterMessage }} <br>


                <div class="clearfix"></div>

            </form>



            </div>
            {% for message in messages %}
              <div class="row">
                  <!-- <div class="col-lg-7 col-lg-offset-4">-->
                    <br>
                    {% if 'success' in message.tags %}
                    <div class="alert alert-success col-lg-4 col-lg-offset-4" role="alert"><center><strong>{{ message }}</strong></center></div>
                    {% endif %}
                    {% if 'error' in message.tags %}
                    <div class="alert alert-danger col-lg-4 col-lg-offset-4" role="alert"><!-- <center>{{message}}<strong>{{ form.errors }}</strong></center><small>{{ form.non_field_errors.message | striptags }}</small> -->{{message}}

                        {% if form.non_field_errors %}
                             <label>  {{form.non_field_errors}} </label>
                        {% endif %}
                        <br>
                        {% if form.errors.adresa_email %}
                            <label>  {{form.errors.adresa_email}} (adresa de email)</label> <br>
                        {% endif %}
                    </div>
                    {% endif %}

                  </div>
              <!-- </div> -->
            {% endfor %}
          </div>
        </div>
    </div>
    <!-- /.container -->




{% endblock content %}

src/home/templates/index.html
{% extends 'base.html' %}
<!-- -->
{% block metatags %}
    <meta name="google-site-verification" content="_kKMOjMxqNKLEiBffYvqD9TeDLQkGnGNgBheOH62NoI" />
    <meta name="description" content="Selfpower comunitate de consiliere si dezvoltare personala. Consiliere. Cursuri. Educatie. Blog">
    <meta name="keywords" content="Selfpower, Consiliere, Dezvoltare, Personala, Comunitate, Studiu, Blog">
    <meta property="og:title" content="Acasa - Selfpower Consiliere, Educatie si Dezvoltare Personala" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="https://selfpower.ro" />
    <meta property="og:description" content="Selfpower comunitate de consiliere si dezvoltare personala. Evenimente. Cursuri. Educatie. Blog" />
    <meta property="og:image" content="https://selfpower.ro/static/img/ParkGreenxs.jpg" />
    <meta property="og:image:secure_url" content="https://selfpower.ro/static/img/ParkGreenxs.jpg" />
    <meta property="og:image:type" content="image/jpeg" />
    <meta property="og:image:width" content="717" />
    <meta property="og:image:height" content="403" />
{% endblock metatags %}
{% block title %} Acasa - Selfpower Consiliere, Educatie si Dezvoltare Personala{% endblock title %}

{% load static %}

{% block body %} <body id="home"> {% endblock body %}

{% block content %}
 
    <div class="container">

        <div class="row">
            <div class="box">
                <div class="col-lg-10 col-lg-offset-1 text-center">
                <img src="{% static "img/banner.png" %}" alt="Blog Image" class="img-responsive center-block">
                </div>
            </div>
        </div>

        <div class="row">
            <div class="box">
                <div class="col-lg-6 col-lg-offset-3 text-center">
                    <hr>
                    <p class="frontpage">"M-am str&#259;duit ne&#238;ncetat s&#259; nu ridiculizez, s&#259; nu depl&#226;ng <br>&#351;i nici s&#259; dispre&#355;uiesc ac&#355;iunile umane, ci s&#259; le în&#355;eleg."<br>Spinoza</p>
                    <hr>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="box">
                <div class="col-lg-10 col-lg-offset-1">
                    <hr>
                    <h2 class="intro-text text-center">Cercetare
                        <strong>Stresul Emigranților</strong>
                    </h2>
                    <hr>
                    <img class="img-responsive img-border img-left" src="{{MEDIA_URL}}/img/JaquesRallPhotographyFrankfurtamMain2xs.jpg" alt="">
                    <hr class="visible-xs">
                    <small>
                    <p>
                      Am ales sa fac aceasta cercetare din dorinta de a oferi un sprijin emigrantilor romani din Germania, si ca urmare a propriei experiente de emigrant in Germania.
                    </p>
                    <p class="text-justified blog">
                      Inainte de a avea eu insumi aceasta experienta, consideram ca nu este atat de dificil sa ma adaptez intr-o noua tara, dar nu am luat in calcul toti factorii care ar putea sa perturbe procesul de adaptare la o noua cultura si consecintele care pot aparea in urma unui pas atat de important.
                    </p>
                    </small>
                    <ul class="pager">
                        <li>
                          <a href="https://selfpower.ro/blog/stresul-emigrantilor-romani-din-germania">Citește mai mult &rarr;</a>
                        </li>
                    </ul><!-- ./pager -->
                </div>
            </div>
        </div>

        <div class="row">
          <div class="box">
            <div class="row">
            <form id="inregistrare" class="form-inline text-center" action="" method="POST">
              {% csrf_token %}
                <div class="form-group">
                  <label for="email_address">Newsletter:</label>
                  <input type="email" class="form-control" name="adresa_email" id="id_adresa_email" placeholder="nume@nume.com">
                  </div>
                <button type="submit" class="btn btn-default">Înscriere</button>
            </form>
            </div>
            {% for message in messages %}
              <div class="row">
                  <div class="col-lg-6 col-lg-offset-3">
                    <br>
                    {% if 'success' in message.tags %}
                    <div class="alert alert-success" role="alert"><center><strong>{{ message }}</strong></center></div>
                    {% endif %}
                    {% if 'error' in message.tags %}
                    <div class="alert alert-danger" role="alert"><center><strong>{{ message }}</strong></center>{{ form.errors }}<small>{{ form.non_field_errors | striptags }}</small></div>
                    {% endif %}
                  </div>
              </div>
            {% endfor %}
          </div>
        </div>

    </div>
    <!-- /.container -->

{% endblock content %}

src/home/templates/parteneri.html
{% extends 'base.html' %}

{% block metatags %}
    <meta name="description" content="Partenerii asociatiei Selfpower">
    <meta name="keywords" content="Selfpower, asociatie, colaboratori, parteneri, membrii">
    <meta property="og:title" content="Partenerii nostri" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="https://www.selfpower.ro/parteneri" />
    <meta property="og:description" content="Despre partenerii asociatiei Selfpower" />
    <meta property="og:image" content="https://www.selfpower.ro/static/img/ParkGreenxs.jpg" />
    <meta property="og:image:secure_url" content="https://www.selfpower.ro/static/img/ParkGreenxs.jpg" />
    <meta property="og:image:type" content="image/jpeg" />
    <meta property="og:image:width" content="717" />
    <meta property="og:image:height" content="403" />
{% endblock metatags %}
{% block title %} Despre Noi - Selfpower Consiliere, Educatie si Dezvoltare Personala{% endblock title %}

{% load static %}

{% block body %} <body id="home"> {% endblock body %}

{% block content %}

<div class="container">

  <div class="row">
        <div class="box">



            <div class="col-sm-2 col-sm-offset-3 text-center">
                <a class="intro-text text-center" href="https://avproiect.com/">AVPro<span style="color: orange">i</span>ect.com
                  
                </a> 
                <hr>
            </div>


            <div class="col-sm-2 col-sm-offset-3">
                    <img class="img-responsive" src="{% static "img/ltn2.jpg" %}" alt="LTN">
            </div>
  
        </div>


  </div>
</div>
</body>

{% endblock content %}