src/hub/urls.py
'''
hub/urls
'''
from django.urls import path
from .views import ProiecteIndex, ProiecteDetail

urlpatterns = [
    path(r'', ProiecteIndex.as_view(), name='proiecte_index'),
    path(r'<slug>', ProiecteDetail.as_view(), name="proiecte_detail"),
    # path(r'resurse/<slug>', ResurseDetail.as_view(), name="resurse_detail"),
    # path(r'resurse/', ResurseIndex.as_view(), name='resurse_index'),

    # membership, feature not offered yet. No link to this page.
    # path(r'membership/', membership, name='membership'),
]

src/hub/models.py
'''
post_save: trigger a function to run at creation of an instance
'''
from django.db import models
from django.db.models.signals import post_save
from django.urls import reverse
from django.db.models.signals import post_delete
from django.dispatch import receiver

from SelfpowerProject.settings.utils import prepare_you_tube_url

class ProjectQuerySet(models.QuerySet):
    '''
    A query set model.
    '''
    def published(self):
        '''
        Return project posts that are published
        '''
        return self.filter(publish=True)


class Proiect(models.Model):
    '''
    Proiect
    '''
    title = models.CharField(max_length=200)
    text = models.TextField()
    slug = models.SlugField(max_length=40, unique=True)
    publish = models.BooleanField(default=True)
    objects = ProjectQuerySet.as_manager()
    # profile = models.FileField(upload_to = 'hubImages/',blank=True,null=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        '''
        Get absolute url of object proiect
        '''
        return reverse("proiecte_detail", kwargs={"slug": self.slug})

    class Meta:
        verbose_name_plural = "Proiecte"
        verbose_name = "Proiect"
        ordering = ["id"]


class Image(models.Model):
    '''
    Object that references an image for different other models
    '''
    image = models.FileField(upload_to='hubImages/', blank=False)
    proiect = models.ForeignKey(Proiect, on_delete=models.CASCADE, related_name='images')


@receiver(post_delete, sender=Image)
def submission_delete(sender, instance, **kwargs):
    instance.image.delete(False) 


class Resursa(models.Model):
    '''
    Resursa model. No longer used in the project
    It was deactivated on client's wish.
    It's similar to a blog structure but contains in addition
    on video url and a different image field.
    '''
    title = models.CharField(max_length=200)
    text = models.TextField()
    slug = models.SlugField(max_length=40, unique=True)
    videoUrl = models.CharField(max_length=300, blank=True)
    profile = models.FileField(upload_to='hubImages/')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "resurse"

    def save(self, *args, **kwargs):
        '''
        Overwriting save()
        '''
        self.videoUrl = prepare_you_tube_url(self.videoUrl)
        super(Resursa, self).save(*args, **kwargs)


class BookUrl(models.Model):
    '''
    Ideally this should represet a book.
    Contains a title, the a reference to a resursa model and
    the url to the pdf/file.
    '''
    url = models.CharField(max_length=300)
    title = models.CharField(max_length=200)
    resursa = models.ForeignKey(Resursa, on_delete=models.DO_NOTHING)

    class Meta:
        '''
        Verbose names; contain translations in romanian
        '''
        verbose_name = "carte"
        verbose_name_plural = "carti"

src/hub/views.py
'''
hub/views
'''
from django.shortcuts import render
from django.views import generic
from hub.models import Proiect, Image, Resursa, BookUrl

from backend.procceses import isSFA

from django.conf import settings # for debug
from django import template

# Create your views here.
register = template.Library()


class ProiecteIndex(generic.ListView):
    '''
    ListView for proiecte model
    '''
    template_name = "proiecte_index.html"
    paginate_by = 10

    def get_context_data(self, **kwargs):
        '''
        Get list of proiecte that are published
        Customized query set for sitemaps.py
        '''
        context = super(ProiecteIndex, self).get_context_data(**kwargs)
        context['Proiect'] = Proiect.objects.published()
        return context

    def get_queryset(self):
        queryset = Proiect.objects.get_queryset().order_by('id').prefetch_related('images').published()
        return queryset
 


class ProiecteDetail(generic.DetailView):
    '''
    DetailView for proiecte model
    '''
    model = Proiect
    template_name = "proiecte_detail.html"

    def get_context_data(self, **kwargs):
        context = super(ProiecteDetail, self).get_context_data(**kwargs)
        slug = self.kwargs['slug']

        images_urls = list()

        for instance in Image.objects.filter(proiect__in=Proiect.objects.filter(slug=slug)):
            images_urls.append(instance.image.url)

        if settings.DEBUG:
            for obj in images_urls:
                print("hub.ProiecteDetail.images_urls.obj: ", obj)

        context['images'] = images_urls

        if settings.DEBUG:
            context_messafe = str(context).encode('utf-8')
            print(context_messafe)

        # And so on for more models
        return context



class ResurseIndex(generic.ListView):
    '''
    Listview for Resursa model
    '''
    model = Resursa
    template_name = "resurse_index.html"
    paginate_by = 15

    def get_context_data(self, **kwargs):
        context = super(ResurseIndex, self).get_context_data(**kwargs)

        context['resurse'] = Resursa.objects.all()

        # And so on for more models
        return context




class ResurseDetail(generic.DetailView):
    '''
    DetailView for Resursa model
    '''
    model = Resursa
    template_name = "resurse_detail.html"

    def get_context_data(self, **kwargs):
        context = super(ResurseDetail, self).get_context_data(**kwargs)
        slug = self.kwargs['slug']

        context['books'] = BookUrl.objects.filter(resursa=Resursa.objects.filter(slug=slug))
        context['videoUrl'] = embed_url(Resursa.objects.filter(slug=slug).first().videoUrl)

        return context


def embed_url(video_url):
    '''
    Transform an clickable youtube url into an embeded one for a frame
    '''
    new_adress = video_url.replace("watch?v=", "embed/")
    print(new_adress)
    return new_adress


def membership(request):
    '''
    Webview
    '''
    return render(request, 'membership.html', {'isSFA':isSFA})

src/hub/templates/proiecte_detail.html
{% extends "blog_base.html" %}
{% load django_markdown %}
{% load static %}

{% block metatags %}
    <meta name="description" content="{% block metadesc %}{% if object.title %}{{ object.title }}{% else %}Proiecte ale Asociatiei Selfpower ONG Detalii.{% endif %}{% endblock metadesc %}">
    <meta name="keywords" content="Selfpower, Proiecte, Activitati, Evenimente, Colaborari, Actiuni, Workshopuri, Workshop-uri, Educatie, Tabere, Dezvoltare, Personala">
    <meta name="author" content="Echipa Selfpower.ro">
    <meta property='article:publisher' content='https://www.selfpower.ro' />
    <meta property='og:site_name' content='Asociatia Selfpower' />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="{{ request.scheme }}://{{request.META.HTTP_HOST}}/proiecte/{{ object.slug }}" />
    <meta property="og:title" content="{% block metatitle %}{% if object.title %}{{ object.title }}{% else %}Proiect Selfpower.ro{% endif %}{% endblock metatitle %}" />
    <meta property="og:description" content="Selfpower - Proiecte, Activitati, Tabere, Evenimente, Educatie, Dezvoltare, Personala" />
    <meta property="og:image" content="{% if images %}{{ request.scheme }}://{{request.META.HTTP_HOST}}{{ images.0 }}{% else %}https://www.selfpower.ro/static/img/banner.png{% endif %}" />
    <meta property="og:image:secure_url" content="{% if images %}{{ request.scheme }}://{{request.META.HTTP_HOST}}{{ images.0 }}{% else %}https://www.selfpower.ro/static/img/banner.png{% endif %}" />
    <meta property="og:image:type" content="{% if images %}image/jpg{% else %}image/png{% endif %}" />
    <meta property="og:image:alt" content="Proiect Post Image" />
    {% if images %}
    {% else %}
    <meta property="og:image:width" content="1000" />
    <meta property="og:image:height" content="532" />
    {% endif %}
    <meta property="fb:app_id" content="2521504124841472" />
{% endblock metatags %}



{% block title %}  {{ object.title }} {% endblock title %}


{% block body %} <body id="proiecte"> {% endblock body %}



{% block content %}

<div class="container">
  <div class="box">

      <div class="row">

          <div class="col-lg-10 col-lg-offset-1">
              <hr>
              <h2 class="intro-text text-center"><strong>Proiect</strong>
                  Selfpower
              </h2>
              <hr>
          </div>

      </div><!-- ./row -->

      <div class="row">
        <div class="col-md-10 col-md-offset-1">
          {% comment %}
             Because bootstrap needs active element, we need to check:
             - if more than 1 img, show carousel, loop, make first one active
             - if only 1 image, show it
             - if no images exist, fallback to default image
          {% endcomment %}
          {% if images|length > 1 %}
                <div id="myProjectCarousel" class="carousel slide">
                    <div class="carousel-inner" style="height:350px; background:darkgray">
                    {% for url in images %}
                      {% if forloop.counter == 1 %}
                          <div class="item active">
                             <img src="{{url}}" alt="image one" class="img-responsive img-border center-block" style="max-height:350px">
                          </div>
                      {% else %}
                          <div class="item ">
                              <img src="{{url}}" alt="proiect image" class="img-responsive img-border center-block" style="max-height:350px">
                           </div>
                      {% endif %}
                    {% endfor %}
                    </div><!-- ./carousel-inner -->
                    <ol class="carousel-indicators">
                      <!-- Here we need a count on url items -->
                      <!-- said Razvan on 4th April 2019 -->
                      {% for url in images %}
                         {% if forloop.counter == 1 %}
                            <li data-target="#myProjectCarousel" data-slide-to="0" class="active"></li>
                         {% else %}
                            <li data-target="#myProjectCarousel" data-slide-to="1"></li>
                         {% endif %}
                       {% endfor %}
                    </ol>
                    <a class="left carousel-control" href="#myProjectCarousel" data-slide="prev">
                        <span class="icon-prev"></span>
                    </a>
                    <a class="right carousel-control" href="#myProjectCarousel" data-slide="next">
                        <span class="icon-next"></span>
                    </a>
                </div><!-- ./myProjectCarousel-->
          {% elif images|length > 0 %}
          <div class="col-lg-12 text-center">
              <img class="img-responsive img-border" src="{{ images | first }}" alt="proiect image" style="max-height:350px">
          </div>
          {% else %}
          <div class="col-lg-12 text-center">
              <img class="img-responsive img-border img-full" src="{% static "img/banner.png" %}" alt="default image">
          </div>
          {% endif %}
        </div>
      </div><!-- ./row -->

      <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="blogpost">
                  <h2 class="text-center">{{object.title}}
                      <br>
                      <hr>
                  </h2>
                  {{ object.text | markdown }}
                  <hr>
                </div>
            </div><!-- ./col-md-10 -->
      </div><!-- ./row -->

      <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <div id="disqus_thread"></div>
          <script>
          /**
          *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
          *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
          var disqus_config = function () {
          this.page.url = 'https://selfpower.ro{% url "proiecte_detail" slug=object.slug %}';  // Replace PAGE_URL with your page's canonical URL variable
          this.page.identifier = 'selfpower-proiect-{{ object.slug }}'; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
          };
          (function() { // DON'T EDIT BELOW THIS LINE
          var d = document, s = d.createElement('script');
          s.src = 'https://selfpower-ro.disqus.com/embed.js';
          s.setAttribute('data-timestamp', +new Date());
          (d.head || d.body).appendChild(s);
          })();
          </script>
          <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
        </div>
      </div><!-- ./row -->

  </div> <!-- box -->
</div> <!-- container -->


{% endblock %}

src/hub/templates/proiecte_index.html
{% extends 'blog_base.html' %}
{% load static %}

{% block metatags %}
    <meta name="description" content="Proiecte, Activitati, Evenimente, Colaborari, Actiuni, Workshopuri, Workshop-uri, Educatie, Tabere de Dezvoltare Personala">
    <meta name="keywords" content="Selfpower, Proiecte, Activitati, Evenimente, Colaborari, Actiuni, Workshopuri, Workshop-uri, Educatie, Tabara, Tabere, Dezvoltare, Personala">
    <meta property="og:type" content="website" />
    <meta property="og:url" content="https://www.selfpower.ro/proiecte" />
    <meta property="og:title" content="Proiecte, Evenimente, Colaborari, Workshop-uri - Selfpower.ro" />
    <meta property="og:description" content="Proiecte, Activitati, Evenimente, Colaborari, Actiuni, Workshopuri, Workshop-uri, Educatie, Tabere Dezvoltare Personala" />
    <meta property="og:image" content="https://www.selfpower.ro/static/img/banner.png" />
    <meta property="og:image:secure_url" content="https://www.selfpower.ro/static/img/banner.png" />
    <meta property="og:image:type" content="image/png" />
    <meta property="og:image:alt" content="Proiecte Image" />
    <meta property="og:image:width" content="1000" />
    <meta property="og:image:height" content="532" />
    <meta property="fb:app_id" content="2521504124841472" />
{% endblock metatags %}

{% block title %} Proiecte, Evenimente, Colaborari, Workshop-uri - Selfpower.ro{% endblock title %}

{% block body %} <body id="proiecte"> {% endblock body %}


{% block content %}

    <div class="container">
    <div class="row">
    <div class="box">
            <div class="col-lg-10 col-lg-offset-1">
                <hr>
                <h2 class="intro-text text-center"><strong>Proiecte</strong>
                    Selfpower
                </h2>
                <hr>
            </div>
    </div><!-- ./box -->
    </div><!-- ./row -->
    </div><!-- ./container-->



    <div class="container">
       	{% for item in proiect_list %}
           <div class="row">
             <div class="box">
                <div class="col-lg-10 col-lg-offset-1">
                  <h2 class="text-center">
                    <a href="{% url "proiecte_detail" slug=item.slug %}"> {{item.title}} </a>
                  </h2>
                  <br>
                      <a href="{% url "proiecte_detail" slug=item.slug %}">
                        {% if item.images.all.0.image.url %}
                        <img  src="{{ item.images.all.0.image.url }}"
                              alt="banner img proiecte"
                              style="width: 70%;"
                              class="img-responsive center-block">
                        {% else %}
                        <img  src="{% static "img/blogimage.jpg" %}"
                              alt="Blog Image"
                              style="width: 70%;"
                              class="img-responsive center-block">
                        {% endif %}
                      </a><!-- or style="max-height:225px" -->
                       <br>
                </div><!-- /.col-lg-10 -->
              </div>
           </div><!-- /.row -->
        {% endfor %}
    </div><!-- /.container -->

{% endblock content %}